# Generated by Django 4.2.5 on 2023-09-06 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_owners', models.IntegerField()),
                ('registration_number', models.TextField(unique=True)),
                ('manufacture_year', models.IntegerField()),
                ('number_of_doors', models.IntegerField(default=5)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarModel.carmodel')),
            ],
        ),
    ]
