# Generated by Django 4.2.5 on 2023-09-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('car_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.TextField()),
                ('model', models.TextField()),
            ],
            options={
                'unique_together': {('make', 'model')},
            },
        ),
    ]
