# Generated by Django 4.2.5 on 2023-09-07 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_app', '0001_initial'),
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_date', models.DateField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car')),
                ('seller_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUser.appuser')),
            ],
        ),
    ]
