# Generated by Django 4.2.5 on 2023-09-07 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='advertisement_date',
        ),
    ]
