# Generated by Django 4.2.5 on 2023-09-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.TextField(max_length=50)),
                ('street_number', models.BigIntegerField()),
                ('zip_code', models.BigIntegerField()),
                ('city', models.TextField(max_length=50)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUser.appuser')),
            ],
        ),
    ]
