# Generated by Django 4.2.5 on 2023-09-06 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Car', '0001_initial'),
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisement_id', models.AutoField(primary_key=True, serialize=False)),
                ('advertisement_date', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUser.appuser')),
            ],
        ),
    ]
